name: Varithms
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.2.0
  cached_network_image: ^2.0.0-rc
  firebase_database: ^3.1.1
  cloud_firestore: 0.13.7
  firebase_auth: ^0.15.3+1
  http: ^0.12.0+2
  fluttertoast: ^3.1.3
  google_sign_in: 4.0.1+1
  shared_preferences: 0.5.8
  country_code_picker: 1.4.0
  flutter_phoenix: 0.1.0
  liquid_progress_indicator: 0.3.2
  flutter_tindercard: 0.1.9
  carousel_slider: 2.2.1
  flutter_custom_clippers: 1.1.1
  flutter_webview_plugin: ^0.3.10+1
  email_validator: 1.0.5
  image_picker: 0.6.7+6
  firebase_storage: ^3.0.6
  url_launcher: 5.5.0
  wave: ^0.0.8
  flutter_tts_improved: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/




  fonts:
    - family: Livvic
      fonts:
        - asset: assets/fonts/Livvic_Light.ttf
    - family: Aquire
      fonts:
        - asset: assets/fonts/Aquire.otf
        - asset: assets/fonts/AquireLight.otf
